### ISSUE TITLE
Does this work offline? and package apps for you ? 

### ISSUE THREAD

**Issue by rwatts3** [jrudio/meteor-electron#12]
Greetings, 

I have seen the project electrometeor, and now I have come across this one. 
I am curious as to which one offers more features such as working purely offline, 
and allowing in app updates to be pushed as meteor cordova does? 

Could you give me a little insight on this package?

Thank you, 

Ryan

**Comment by jrudio** [comment]
Hi, currently this package is still in its infancy stage. Ideally that's where I would like to take it (work offline), but this project has been put on the backburner, as I have been extremely busy.

All it pretty much does, right now, is run `electron-prebuilt` when running meteor on startup. The idea here is to help run electron when you are writing your meteor app. Then, when you want to package your meteor app into electron you just change a variable in `settings.json` to true and it will output it into your project folder (`.electron/output`).

Again, this package is not very helpful at this time, but electrometeor is definitely more supported and has more features(?). I believe you still have to code some things yourself though, as far as working offline.
