### ISSUE TITLE
Electron doesn't work on Meteor Windows

### ISSUE THREAD

**Issue by mdingena** [jrudio/meteor-electron#16]
C:\Users\mdingena\app>meteor add jrudio:electron
    
    Changes to your project's package version selections:
    
    jrudio:electron  added, version 0.0.21
    
    
    jrudio:electron: Run your Meteor app in Electron
    
    C:\Users\mdingena\app>meteor
    [[[[[ C:\Users\mdingena\app ]]]]]
    
    => Started proxy.
    => Started MongoDB.
    I20150929-10:19:39.661(2)? 'node' is not recognized as an internal or external command,
    I20150929-10:19:39.664(2)? operable program or batch file.
    I20150929-10:19:42.947(2)? Failed to start electron.
    I20150929-10:19:42.950(2)? https://github.com/jrudio/meteor-electron/blob/dependency/main.js
    I20150929-10:19:42.947(2)? Please create a main.js and package.json, then put it into .electron/electronApp/ or download it from:
    I20150929-10:19:42.951(2)? https://github.com/jrudio/meteor-electron/blob/dependency/package.json
    I20150929-10:19:42.959(2)? Downloading package.json...
    => Started your app.
    
    => App running at: http://localhost:3000/
       Type Control-C twice to stop.
    
    I20150929-10:19:43.634(2)? Downloading package.json ...
    I20150929-10:19:43.640(2)? Finished downloading package.json
    I20150929-10:19:43.643(2)? Downloading main.js ...
    I20150929-10:19:43.645(2)? Finished downloading main.js
    I20150929-10:19:44.863(2)? Starting Electron...
    I20150929-10:19:44.945(2)? The system cannot find the path specified.

![image](https://cloud.githubusercontent.com/assets/13388489/10158713/2eb1c6c2-6694-11e5-94a1-db8e6bd73397.png)

**Comment by jrudio** [comment]
It looks like you don't have node installed.

In the next update I want to depend on meteor's node, as it is shipped with
meteor. So users don't have to have to install node, and just use the one
that comes with meteor.

**Comment by mdingena** [comment]
That's correct, I do not have node.js installed, because I want to use Meteor out of the box (with their official Windows support as of version 1.2).

I am looking forward to your Electron update!

**Comment by jrudio** [comment]
Awesome!

I had completely forgot about the `develop` branch. It doesn't utilize node to install the npm electron-prebuilt. So it's actually already done. Although, last time I tested out the branch there were some other non-related errors on windows. So that is something I got to fix and publish.

**Comment by jrudio** [comment]
Published latest version
