### ISSUE TITLE
1.2 Support

### ISSUE THREAD

**Issue by sangyoo91** [jrudio/meteor-electron#17]
```
error: unknown package: isobuild:compiler-plugin
Required by: meteor 1.1.9
Required by: ecmascript 0.1.3-rc.0
Required by: ecmascript 0.1.3-rc.0
```
I am getting the following error.

**Comment by jrudio** [comment]
Sorry for the late reply.

I thought I had the latest version published to Atmosphere, but apparently that wasn't the case*. I just published a new version of the package that uses 1.2.

*I had it sitting on the `develop` branch, but never published it. So I'm an idiot for that.

**Comment by oorabona** [comment]
Hello @jrudio 

I am not seeing it anywhere when I do a:
```
$ meteor show jrudio:METEOR --show-all
Release: jrudio:METEOR                        
Maintainers: jrudio                           
                                              
meteor extended with desktop support          
                                              
Versions:                                     
  1.1        August 30th, 2015     (recommended)
  1.1.0-rc0  September 3rd, 2015
  1.1.0      September 1st, 2015   (recommended)
  1.1.1      August 28th, 2015

Experimental versions:                        
  1.1.1_2  August 28th, 2015                  
  1.1.1_4  August 28th, 2015
  1.1.1_5  August 29th, 2015
  1.1.1_6  August 29th, 2015
```
:cry:

**Comment by jrudio** [comment]
Unfortunately, that is correct. I updated the [`electron`](https://github.com/jrudio/meteor-electron) package to 1.2, not the modified [Meteor](https://github.com/jrudio/meteor) build. Which is still 1.1 as you are seeing.

**Comment by oorabona** [comment]
If I understand right, the package is here to help ipc with electron while the meteor release is here to ease the building process. That is correct ? I might be a bit offtopic then, but do you plan to release a compatible version for Meteor 1.2 ? At the moment I could figure out how to build with electrify / electron but I'd rather prefer the run-desktop way :smile:

Thanks !

**Comment by jrudio** [comment]
:smile: Hah, yes, that's pretty much the idea behind the package and meteor release.

Making a release for 1.2 should be fairly easy... I'll probably have time this weekend to get it going.
