### ISSUE TITLE
Electron-packager Integration

### ISSUE THREAD

**Issue by jrudio** [jrudio/meteor-electron#2]
I understand this can be done manually, but why not? Just flick a switch and your meteor app will be ran off of an executable.

I will be using this page to collect my thoughts on what should/needs to be done. Anyone reading this, your input is welcomed.

**Comment by jrudio** [comment]
Run a modified version of electron-packager that reads from the .electron/ folder. Or, an alternative would be to add the downloaded electron to the PATH, and then run electron-packager.

**Comment by hell000** [comment]
Maybe offer option to include local mongo or not? 

Regarding including node or not. I think electron uses iojs which uses a newer v8 version than node does. This causes issues with installing fibres.

**Comment by jrudio** [comment]
> Regarding including node or not. I think electron uses iojs which uses a newer v8 version than node does. This causes issues with installing fibres.

Thanks! I did not know there's issues with fibers and iojs.

In your opinion, for including mongo locally, what would be the best option?

When the standalone runs for the first time: download the proper version of mongo (proper as in the hosts machine's version)

^ or is that the only option? lol

**Comment by hell000** [comment]
@sircharleswatson is including both mongo and node in the build.
I haven't been able to build the production version using your package yet since I'm on mac and it's not working atm. 

I was thinking that a local mongo wouldn't be needed for browser like apps or apps that can just get away with a persistent-minimongo. A manual entry in package.json to include mongo or not would be sufficient. Maybe there is a way to check whether the meteor app has any collections set up and include mongo automatically that way?

**Comment by jrudio** [comment]
I'm not sure what the problem could be on mac. I don't have a mac to test it. :(

>I was thinking that a local mongo wouldn't be needed for browser like apps or apps that can just get away with a persistent-minimongo.

Agreed, but for desktop apps that can act as a host rather than a web browser with some access to desktop api('s) should obviously include mongo, not exactly sure how to implement - i'll look into how sircharleswatson does it. Although, I am not sure it's a need, it was an idea that stemmed from this [plex project](https://github.com/lokenx/plexrequests-meteor).

> A manual entry in package.json to include mongo or not would be sufficient. Maybe there is a way to check whether the meteor app has any collections set up and include mongo automatically that way?

It's definitely doable [using another package](https://github.com/dburles/mongo-collection-instances).
