### ISSUE TITLE
Cert Untrusted

### ISSUE THREAD

**Issue by patrickml** [jrudio/meteor-electron#20]
I just a tried to add the package and this is the error(s) I am receiving when my app starts up

```
Downloading electron-v0.26.0-darwin-x64.zip
I20151118-16:44:18.152(-5)? Error: CERT_UNTRUSTED
I20151118-16:44:18.152(-5)?
I20151118-16:44:18.152(-5)? /Users/patricklewis/.meteor/packages/jrudio_electron/.0.0.21.8qe07r++os+web.browser+web.cordova/npm/
node_modules/electron-prebuilt/install.js:15
I20151118-16:44:18.152(-5)?   throw err
I20151118-16:44:18.152(-5)?         ^
I20151118-16:44:18.158(-5)? Error: CERT_UNTRUSTED
I20151118-16:44:18.964(-5)? Starting Electron...
=> Started your app.

=> App running at: http://localhost:3000/
I20151118-16:44:19.073(-5)? /bin/sh: /home/jrudio/meteor/meteor-electron/.npm/package/node_modules/electron-prebuilt/dist/electr
on: No such file or directory
```

**Comment by jrudio** [comment]
Hmm... looked into it, as it shouldn't be downloading the .zip manually (that was in the old version), and figured out I did not publish whatever is on the `develop` branch (and forgot to merge to `master`) to Atmosphere.

So I will post back when I publish the package!

**Comment by jrudio** [comment]
I published a new version, and you shouldn't be presented with that error!

Let me know if you have any issues!

**Comment by patrickml** [comment]
It seems like im getting another error now

```
W20151119-14:34:40.050(-5)? (STDERR)
W20151119-14:34:40.050(-5)? (STDERR) events.js:72
W20151119-14:34:40.050(-5)? (STDERR)         throw er; // Unhandled 'error' event
W20151119-14:34:40.050(-5)? (STDERR)               ^
W20151119-14:34:40.052(-5)? (STDERR) Error: spawn ENOENT
W20151119-14:34:40.053(-5)? (STDERR)     at errnoException (child_process.js:1011:11)
W20151119-14:34:40.053(-5)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by jrudio** [comment]
Damn, it looks like I forgot to put an error check when executing Electron.

**Comment by Jayuda** [comment]
+1

**Comment by maximebodereau** [comment]
I have the same problem 
----
W20151222-14:01:18.858(-5)? (STDERR)
W20151222-14:01:18.859(-5)? (STDERR) events.js:72
W20151222-14:01:18.859(-5)? (STDERR)         throw er; // Unhandled 'error' event
W20151222-14:01:18.859(-5)? (STDERR)               ^
W20151222-14:01:18.859(-5)? (STDERR) Error: spawn ENOENT
W20151222-14:01:18.859(-5)? (STDERR)     at errnoException (child_process.js:1011:11)
W20151222-14:01:18.860(-5)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by thomasf1** [comment]
Any updates on this?

**Comment by jrudio** [comment]
Just pushed an update that handles the error, and fixed the cause of that error.
