### ISSUE TITLE
Not work when run "meteor"?

### ISSUE THREAD

**Issue by yuomtheara** [jrudio/meteor-electron#5]
I try create the "testing" app.
And then add `meteor-electron` package, but when i run `meteor` cammand it show error:
`
I20150513-16:55:58.732(7)? The system cannot find the path specified.
`
I base on win 7 64bit (D:\app\meteor\testing\...).

**Comment by jrudio** [comment]
I named the package just 'electron'. Did you try meteor add jrudio:electron? Also, do you have the latest version 0.0.7?

**Comment by jrudio** [comment]
I just tested it on my windows machine and I am getting the same error. Will get a fix out in a couple of hours.

**Comment by jrudio** [comment]
@yuomtheara Can you test the new version v0.0.18? I have it working on my end on Windows and Linux. Sorry for the wait(If you were waiting, lol).

**Comment by yuomtheara** [comment]
Thanks now it work fine.
