### ISSUE TITLE
Could I create shortcut or .exe file to run "meteor" instead of cmd?

### ISSUE THREAD

**Issue by thearabbit** [jrudio/meteor-electron#6]
Could I create shortcut or .exe file to run "meteor" instead of cmd?
Thanks  a lot for your helping.

**Comment by jrudio** [comment]
If you know where your Meteor is installed (usually in C:\Users\<your-name>\AppData\Local\.meteor\meteor.bat) then I believe you can create a shortcut to that. In the future I plan on integrating starting up meteor via the packaged up Meteor app.

**Comment by yuomtheara** [comment]
Sorry, not run `meteor.bat`.
I want to run my project app like `D:\app\meteor\testing>meteor` in cmd.

**Comment by jrudio** [comment]
https://gist.github.com/jrudio/0e232661aca06a80c17c

Paste that into  `run-meteor.bat`


Then you can just click on that bat to run the project located in     `D:\app\meteor\testing`

**Comment by yuomtheara** [comment]
I save it on desktop, but it show
```
run: You're not in a Meteor project directory.

To create a new Meteor project:
  meteor create <project name>
For example:
  meteor create myapp

For more help, see 'meteor --help'.

C:\Users\Theara\Desktop>
```
When I save it on my project it work fine.
Could I save it on desktop? and run it in background (don't show cmd dialog).

**Comment by jrudio** [comment]
Oh, you need to add `D:` for the first line. 
```
D:
cd app\meteor\testing
start meteor
```
I'm not sure about hiding cmd. There probably is a way to do it, though.

**Comment by yuomtheara** [comment]
Thanks again,  It work fine.
But when I close the electron form, the cmd not stop (meteor).
So I can't reopen the app, unit I close cmd by manual and then run .bat file again.
What do you think?

**Comment by jrudio** [comment]
Yes. Unfortunately, that is how the package works. I plan on having meteor run for the lifetime of the .exe

**Comment by yuomtheara** [comment]
Wow I wait this :100:

**Comment by jrudio** [comment]
@yuomtheara I have updated the package, if you can test it out that would be awesome!

**Comment by yuomtheara** [comment]
Don't work, when close electron.
`[5568:0519/074955:ERROR:ipc_channel_win.cc(138)] pipe error: 109`

**Comment by jrudio** [comment]
Hmm thhat's weird...oh I believe you have to update your package.json to have:

```javascript
electron: {
  "killMeteorOnExit": true
}
```

and I believe you need to get the new `main.js` from https://github.com/jrudio/meteor-electron/blob/dependency/main.js

If you delete your package.json and `.electron/electronApp/main.js` it downloads it for you. This is my bad as I didn't account for an app that has already added.

**Comment by yuomtheara** [comment]
Thanks, now work fine.

**Comment by thearabbit** [comment]
I wait for .exe file.

**Comment by jrudio** [comment]
Oops, yeah. I put this project on the back-burner for a bit, I will get back to it in a little!
