### ISSUE TITLE
how to add other print menu bar on electron?

### ISSUE THREAD

**Issue by yuomtheara** [jrudio/meteor-electron#7]
I want to print my reports on app, so I need this option on menu bar.
Could???

**Comment by jrudio** [comment]
It's possible, but you would need to do it kind of like this https://github.com/atom/electron/blob/master/docs/api/menu.md

Or, if you don't need the option in the menu bar you can just add window.print() to a button in your meteor project.

**Comment by yuomtheara** [comment]
I will try.
Do you plan to add native menu bar?

**Comment by jrudio** [comment]
Yes, I plan on adding an example menu in the future.

**Comment by yuomtheara** [comment]
thanks.
