### ISSUE TITLE
What the difference with  "sircharleswatson/Electrometeor" ?

### ISSUE THREAD

**Issue by yuomtheara** [jrudio/meteor-electron#8]
What the difference with  "sircharleswatson/Electrometeor" ?

**Comment by jrudio** [comment]
Electrometeor is more advanced than the current state of this meteor package. Electrometeor does it all (for the most part) in the sense that it installs node and mongo so you can make your Meteor application run with just an executable. There's more, but I can't name them off the top of my head.

**Comment by yuomtheara** [comment]
Thanks.
